// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJD4yuUl4MrezBl7z2FQNkCmxDOASEKWg',
    appId: '1:642405673125:web:e1e2a6c0354230b5b8c54c',
    messagingSenderId: '642405673125',
    projectId: 'fir-crashlytics-77c69',
    authDomain: 'fir-crashlytics-77c69.firebaseapp.com',
    storageBucket: 'fir-crashlytics-77c69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnSsDS1fwOOrqFyPrtx0C6N30Vw7Jr-rE',
    appId: '1:642405673125:android:d0bf5be58d55422ab8c54c',
    messagingSenderId: '642405673125',
    projectId: 'fir-crashlytics-77c69',
    storageBucket: 'fir-crashlytics-77c69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBouCDwNRdFiXQxSiiLiucOcbTNCrMl2tA',
    appId: '1:642405673125:ios:b313a4ff7657924cb8c54c',
    messagingSenderId: '642405673125',
    projectId: 'fir-crashlytics-77c69',
    storageBucket: 'fir-crashlytics-77c69.appspot.com',
    iosClientId: '642405673125-78tai9jt1cf5uq7ugafqtkbpp9s0m9c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.democrashlytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBouCDwNRdFiXQxSiiLiucOcbTNCrMl2tA',
    appId: '1:642405673125:ios:b313a4ff7657924cb8c54c',
    messagingSenderId: '642405673125',
    projectId: 'fir-crashlytics-77c69',
    storageBucket: 'fir-crashlytics-77c69.appspot.com',
    iosClientId: '642405673125-78tai9jt1cf5uq7ugafqtkbpp9s0m9c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.democrashlytics',
  );
}
